//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianProfile
    {
        public int GuardianID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Guardian_Type { get; set; }
        public string Email { get; set; }
        public string Alt_Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Home_Phone { get; set; }
        public string Cell_Phone { get; set; }
        public string Work { get; set; }
        public string Fax { get; set; }
        public string Other { get; set; }
        public string Billing { get; set; }
    }
}
