//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadingDataEntities : DbContext
    {
        public ReadingDataEntities()
            : base("name=ReadingDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GuardianProfile> GuardianProfiles { get; set; }
        public virtual DbSet<Stud_Guard_Rel> Stud_Guard_Rel { get; set; }
        public virtual DbSet<Student_Testing_Measurements> Student_Testing_Measurements { get; set; }
        public virtual DbSet<StudentCurrentReadingLevel> StudentCurrentReadingLevels { get; set; }
        public virtual DbSet<StudentHour> StudentHours { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<StudentNote> StudentNotes { get; set; }
        public virtual DbSet<StudentProfile> StudentProfiles { get; set; }
        public virtual DbSet<StudentSchool> StudentSchools { get; set; }
        public virtual DbSet<TestScore_Standard_Raw> TestScore_Standard_Raw { get; set; }
    }
}
