//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentNote
    {
        public int Count { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> RemarkDate { get; set; }
        public string RemarkHeader { get; set; }
        public string Remark { get; set; }
    }
}
