//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Testing_Measurements
    {
        public int Count { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Correct_Words_Each_Minute { get; set; }
        public Nullable<int> Errors { get; set; }
        public Nullable<System.DateTime> Timed { get; set; }
        public Nullable<int> Word_Count { get; set; }
        public string Test_Method { get; set; }
        public string Text_Source { get; set; }
        public string Reading_Level { get; set; }
        public string Passage { get; set; }
    }
}
