//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchool
    {
        public int Count { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string SchoolDist { get; set; }
        public string SchoolName { get; set; }
        public bool Prv_Pub { get; set; }
    }
}
