//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int ID { get; set; }
        public string Campus { get; set; }
        public string InitialDate { get; set; }
        public string FinalDate { get; set; }
        public string Zip_Code { get; set; }
        public string Student { get; set; }
        public string Parent_First_Name { get; set; }
        public string Parent_Last_Name { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Phone_3 { get; set; }
        public string Email_ { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
