//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestScore_Standard_Raw
    {
        public long Index { get; set; }
        public int StudentNo { get; set; }
        public string TestIndex { get; set; }
        public string TestTitle { get; set; }
        public string RawScore { get; set; }
        public string StandardScore { get; set; }
    }
}
